### ISSUE TITLE
Allow entering specific selector(s)

### ISSUE THREAD

**Issue by mgibbs189** [FacetWP/facetwp-conditional-logic#1]
Scenario: sometimes users need to hide not only the facet itself, but also the parent container and/or the label above the facet.

**Comment by mgibbs189** [comment]
Instead of a text box, could this be a textarea within a modal (having monospace font)?

Users may want to include multiple selectors (one per line), and a normal text box will get pretty cramped.

**Comment by mgibbs189** [comment]
* Perhaps use an icon instead of the "Set Selectors" text: https://developer.wordpress.org/resource/dashicons/#editor-code
* Widen the modal popup
* Make the font size smaller in the modal (e.g. 11 or 12px)

**Comment by Desertsnowman** [comment]
For reference to the above comment:
![selectors](https://cloud.githubusercontent.com/assets/307466/14887156/d16e3d16-0d54-11e6-8f65-783dc5c1dabb.gif)

**Comment by Desertsnowman** [comment]
updated button and modal size
![selectors](https://cloud.githubusercontent.com/assets/307466/14909057/575d16c4-0ddf-11e6-958b-144618a568f1.gif)

**Comment by mgibbs189** [comment]
Great!
