### ISSUE TITLE
Add help topics

### ISSUE THREAD

**Issue by Desertsnowman** [FacetWP/facetwp-conditional-logic#13]
@mgibbs189 - uix has a built in help thing. well, need to add help topics here. see https://github.com/FacetWP/facetwp-conditional-logic/blob/ui-rebuild/includes/settings.php#L42-L52

![help](https://cloud.githubusercontent.com/assets/307466/14940403/d773d9b6-0f73-11e6-888f-96c135be008a.gif)

**Comment by mgibbs189** [comment]
I'm not a huge fan of WP's Help pulldown. In my experience, people don't bother to use it and/or notice that it's even there.

I think it'd be better to focus on the [facetwp.com](https://facetwp.com) add-on documentation (once the page goes live). The vast majority of users will hit that page to download the add-on anyways.

We can revisit if needed.
