### ISSUE TITLE
Logic weirdness

### ISSUE THREAD

**Issue by mgibbs189** [FacetWP/facetwp-conditional-logic#14]
The following screenshot has 2 rulesets:

1. Hide the "Region" facet
2. Show the "Region" facet if `Fuel Type` is nuclear

The 2nd ruleset doesn't ever get triggered.

<img src="http://i.imgur.com/wHtwXak.png" />

**Comment by kochhase** [comment]
Yes the conditionals are not working any more after update from 02.05 to now.
![is not working](https://cloud.githubusercontent.com/assets/6199062/14970369/a67b2e30-10c8-11e6-8baf-1b2ace860a41.PNG)

![is not working_2](https://cloud.githubusercontent.com/assets/6199062/14970377/b17439d0-10c8-11e6-8418-dcfd8410c76f.PNG)

**Comment by mgibbs189** [comment]
@kochhase the add-on hasn't been officially released yet...
