### ISSUE TITLE
Add rule for when facet has no available choices

### ISSUE THREAD

**Issue by mgibbs189** [FacetWP/facetwp-conditional-logic#17]
This may require changes to FacetWP itself.

**Comment by kochhase** [comment]
Hi Matts is this allready done in Facetwp?

**Comment by mgibbs189** [comment]
Not yet, it's likely something we'll roll into 2.6 (a few weeks away).

**Comment by mgibbs189** [comment]
The necessary changes are in place for FacetWP 2.6.2 😄 

```js
if (FWP.settings.num_choices['my_facet'] < 0) {
  // hide the facet
}
```

Now we just need to add the condition. @Desertsnowman I'll take a pass at this tomorrow.

**Comment by mgibbs189** [comment]
Starting in FWP 2.6.2, Conditional Logic 1.2:

* Add new ruleset
* Conditions: `<leave blank>`
* Actions: `Hide` > Custom Selector > enter the following into the modal box:

```js
$('.facetwp-facet[data-choices="0"]')
```

This will hide all facets with no available choices. Applies to Checkboxes, Dropdown, fSelect, Hierarchy, and Star Rating field types.

**Comment by mgibbs189** [comment]
Closing, per the "Hide empty facets" section on https://facetwp.com/add-ons/conditional-logic/
