### ISSUE TITLE
Wildcard for URI

### ISSUE THREAD

**Issue by mdorchain** [FacetWP/facetwp-conditional-logic#19]
This is not an issue but a feature request :)
I hope you would consider supporting wildcard (.*) for the uri conditions.
When dealing with taxonomies, this would a be a huge help not having to go through the list of the terms.

**Comment by mgibbs189** [comment]
@mdorchain I like the idea!

**Comment by terrelltechsup** [comment]
I second this.  In the event you use WC Vendors or similar, it would be nice to be able to control facets on /vendors/* such that it effects all stores as apposed to having to create a condition for every single one.

**Comment by mgibbs189** [comment]
(Finally) added to 1.3 milestone :)
