### ISSUE TITLE
"# of results" condition

### ISSUE THREAD

**Issue by mgibbs189** [FacetWP/facetwp-conditional-logic#2]
If # of results is 0, then let users do something (e.g. hide all facet labels, etc)

Same when # of results = 1 (e.g. some users may want to hide facets when there's only 1 result)

**Comment by Desertsnowman** [comment]
oh nice one!

**Comment by mgibbs189** [comment]
Yeah, and we could grab the # of results using `FWP.settings.pager`:

```js
{page: 1, per_page: 4, total_rows: 357, total_pages: 90}
```

**Comment by Desertsnowman** [comment]
done!
