### ISSUE TITLE
Detect empty sliders

### ISSUE THREAD

**Issue by mgibbs189** [FacetWP/facetwp-conditional-logic#22]
If a slider is totally empty, allow it to be hidden too

**Comment by yichenlovetj** [comment]
I need find a way to hide these empty sliders. Is there a way to do this?

**Comment by mgibbs189** [comment]
It's already possible. See the $EMPTY part of the docs, and make sure you're using the latest versions of both FacetWP and the add-on.

**Comment by yichenlovetj** [comment]
oh thanks for the quick customer service, I updated to latest version and its working now, I will give you a five star rating.
