### ISSUE TITLE
Integrate New "Smart Tag" for Checked/In-Use Facets

### ISSUE THREAD

**Issue by AlexJ-GR** [FacetWP/facetwp-conditional-logic#25]
Similar to the $EMPTY "smart tag", although this one targets facets that are checked/in-use

Via a "smart tag", we always want to show facets that are checked so that users can always see them.
The reason for this is to override any programmed rules that would erroneously hide "in-use" or "checked" facets

Upon inspecting the elements:
Unchecked facet = div-class "facetwp-checkbox" 
Checked facet    = div-class "facetwp-checkbox **checked**"

This leads me to believe the "smart tag" would be $CHECKED
1. Create a new ruleset
2. Leave the Conditions blank **(ON: Loaded)**
3. New Action: **SHOW** for the first dropdown, Selector for the second
4. Selector = **$CHECKED.closest('.widget')**

Result: Checked facets are now ALWAYS shown

**Comment by mgibbs189** [comment]
Added a `$ACTIVE` selector, resolved per 0db4ea4
