### ISSUE TITLE
Ruleset drag-and-drop

### ISSUE THREAD

**Issue by mgibbs189** [FacetWP/facetwp-conditional-logic#5]
While not absolutely necessary, I think it'd be nice to support Ruleset drag-and-drop.

We could use jQuery UI or a lightweight library like [Dragula](http://bevacqua.github.io/dragula/) to add a drag handle to each ruleset.

**Comment by Desertsnowman** [comment]
What would you be dragging?

**Comment by mgibbs189** [comment]
Good question - perhaps replace the arrow on the right side with a drag indicator.

**Comment by Desertsnowman** [comment]
I mean,  drag to sort the rulesets? And if so what's the purpose?

**Comment by mgibbs189** [comment]
Yeah, drag each entire ruleset: http://d.pr/i/1lHz9

Users could create rulesets that extend other rulesets. Rulesets at the bottom are executed after the ones on top, so users may want to re-arrange rulesets to get the desired result.

**Comment by Desertsnowman** [comment]
Ok that makes sense and is simple to do.
Just a question. Once a condition had been appeased, does it stop going through other rulesets?

**Comment by Desertsnowman** [comment]
Doh. Read the rest and realised you answered my question.

**Comment by Desertsnowman** [comment]
![sorting](https://cloud.githubusercontent.com/assets/307466/14842988/bd4ceffc-0c4c-11e6-8a0f-62cd71a0412c.gif)

**Comment by mgibbs189** [comment]
Love it!
