### ISSUE TITLE
Ruleset modal - "Remove" button changes

### ISSUE THREAD

**Issue by mgibbs189** [FacetWP/facetwp-conditional-logic#6]
The "Remove" button needs some visual distinction. I've almost clicked it several times, mistaking it for a Cancel button. Possible ideas:

1. Change to red background, or
2. Use a dashicon, e.g. https://developer.wordpress.org/resource/dashicons/#trash

**Comment by Desertsnowman** [comment]
Or make it a trash icon to the right of the footer toolbar

**Comment by Desertsnowman** [comment]
Changed along with 6aae4c1 - this is far better I think.
![remove-ruleset](https://cloud.githubusercontent.com/assets/307466/14843053/4bd94fe0-0c4d-11e6-9f93-2f7eb2d21f6a.gif)

**Comment by mgibbs189** [comment]
Agreed, this is much better
