### ISSUE TITLE
Add show hide effect setting

### ISSUE THREAD

**Issue by Desertsnowman** [FacetWP/facetwp-conditional-logic#7]
Make showing and hiding look a little nicer with a subtle effects

**Comment by Desertsnowman** [comment]
done in 32c1213

**Comment by Desertsnowman** [comment]
![effect-setting](https://cloud.githubusercontent.com/assets/307466/14844696/8f19d052-0c59-11e6-91aa-49b3fbadc77c.png)

**Comment by Desertsnowman** [comment]
Needed to remove slide. caused resize issues.

**Comment by mgibbs189** [comment]
Looks good, closing
