### ISSUE TITLE
"Save Changes" button improvements

### ISSUE THREAD

**Issue by mgibbs189** [FacetWP/facetwp-conditional-logic#8]
1. Use FacetWP's [loading icon](https://github.com/FacetWP/facetwp/blob/master/assets/images/loading.png)
2. Move loading icon to the right of the "Save Changes" text (instead of to the left)
3. After a successful save, replace the loading icon with a [check icon](https://developer.wordpress.org/resource/dashicons/#yes). **Bonus:** make the check icon disappear after a few seconds

Then, we wouldn't need the "Settings saved" info box anymore...

<img src="http://i.imgur.com/rQD8JVD.png" width="680" height="95" />

**Comment by mgibbs189** [comment]
Oh, forgot to mention. Here's the CSS that FacetWP uses to animate the loading icon:

https://github.com/FacetWP/facetwp/blob/master/assets/css/front.css#L44-L52

and

https://github.com/FacetWP/facetwp/blob/master/assets/css/front.css#L177-L222

**Comment by Desertsnowman** [comment]
![saving](https://cloud.githubusercontent.com/assets/307466/14878589/c4a1db7c-0d24-11e6-990d-342f8b6a8b6b.gif)

**Comment by kochhase** [comment]
hi David,
i am testing your last version with the fix above.
But the conditions are not saving. Here my sys report.

`
### WordPress Environment ###

Home URL: http://shareyourboat.de
Site URL: http://shareyourboat.de
WC Version: 2.5.5
Log Directory Writable: ✔
WP Version: 4.5.1
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
Language: de_DE

### Server Environment ###

Server Info: Apache
PHP Version: 7.0.5
PHP Post Max Size: 32 MB
PHP Time Limit: 60
PHP Max Input Vars: 1000
SUHOSIN Installed: –
MySQL Version: 5.5.49
Max Upload Size: 32 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.5.5
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_termmeta: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔

### Active Plugins (32) ###

Ad Inserter: von Spacetime – 1.6.3
All In One WP Security: von Tips and Tricks HQ
Peter
Ruhul
Ivy – 4.0.8

EWWW Image Optimizer: von Shane Bishop – 2.8.0
FacetWP - Conditional Logic: von Matt Gibbs – 0.1
FacetWP: von FacetWP
LLC – 2.4.4

WPBakery Visual Composer: von Michael M - WPBakery.com – 4.11.2.1
Nav Menu Roles: von Kathy Darling – 1.7.9
Ninja Forms: von The WP Ninjas – 2.9.42
Pods - Custom Content Types and Fields: von Pods Framework Team – 2.6.4
Related Posts for WordPress Premium: von Never5 – 1.5.3
Slider Revolution: von ThemePunch – 5.2.5
SearchWP LIKE Terms: von Jonathan Christopher – 2.4.3
SearchWP German Stemmer: von Jonathan Christopher – 1.0.1
SearchWP WooCommerce Integration: von Jonathan Christopher – 1.1.8
SearchWP WP Job Manager Integration: von Jonathan Christopher – 1.5.5
SearchWP: von Jonathan Christopher – 2.7.2
Widget Importer & Exporter: von Steven Gliebe – 1.2.4
WooCommerce: von WooThemes – 2.5.5
WordPress Importer: von wordpressdotorg – 0.6.1
Yoast SEO: von Team Yoast – 3.2.3
WP Editor: von Benjamin Rojas – 1.2.5.3
WP Fastest Cache: von Emre Vona – 0.8.5.6
WP Job Manager - Alerts: von Automattic – 1.4.1
WP Job Manager - Application Deadline: von Automattic – 1.1.5
WP Job Manager - Applications: von Automattic – 2.2.3
WP Job Manager - Bookmarks: von Automattic – 1.2.1
WP Job Manager - Contact Listing: von Astoundify – 1.1.0
WP Job Manager - Extended Location: von Astoundify – 2.3.0
WP Job Manager Field Editor: von Myles McNamara – 1.4.1
WP Job Manager - Predefined Regions: von Astoundify – 1.10.0
WP Job Manager - WooCommerce Paid Listings: von Automattic – 2.7.1
WP Job Manager: von Automattic – 1.25.0

### Settings ###

Force SSL: –
Currency: EUR (€)
Currency Position: left
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2

### API ###

API Enabled: ✔
API Version: 3.1.0



### Taxonomies ###

Product Types: external (external)
grouped (grouped)
job_package (job_package)
job_package_subscription (job_package_subscription)
resume_package (resume_package)
resume_package_subscription (resume_package_subscription)
simple (simple)
variable (variable)


### Theme ###

Name: Listify - Child Theme
Version: 1.0.0
Author URL: http://astoundify.com
Child Theme: ✔
Parent Theme Name: Listify
Parent Theme Version: 1.4 beta

`
![conditional not saving](https://cloud.githubusercontent.com/assets/6199062/14880713/9f7d00a4-0d30-11e6-8cb7-a11e6c4a3594.PNG)

maybe it can help.
Henryk

**Comment by Desertsnowman** [comment]
@kochhase - was it saving prior to this fix?

**Comment by kochhase** [comment]
no yesterday evening not ether

**Comment by Desertsnowman** [comment]
can you clear the browser cache and try again?

**Comment by kochhase** [comment]
yes i will do. And i have deaktived the WP Fastest Cache as well.
see you soon

**Comment by kochhase** [comment]
hi David, i can not save only the conditional without any conditional imput.
See:
![conditional not saving1](https://cloud.githubusercontent.com/assets/6199062/14882370/c2f75c34-0d38-11e6-9079-ecf590d2119b.PNG)

**Comment by kochhase** [comment]
by the way, if you need some admin contact. you can send me an email to hibemeinhardt@agentur-ibe.de.

**Comment by Desertsnowman** [comment]
tried to email you, but got a `Delivery to the following recipient failed permanently...`

**Comment by kochhase** [comment]
yes you are right there is something wrong. here another that is working. mail@henryk-ibemeinhardt.de

**Comment by Desertsnowman** [comment]
@kochhase - thanks that really helped. It was an issue with my object builder. I made the issue on #9 and was fixed in 9eca01d

**Comment by mgibbs189** [comment]
Thanks for the report @kochhase and the fix @Desertsnowman

**Comment by kochhase** [comment]
ok, than i will update and have a new try. thanks for the fast developement!

**Comment by Desertsnowman** [comment]
You're welcome. Thanks so much for the help.
